### ISSUE TITLE
Browser/Accessibility Checklist

### ISSUE THREAD

**Issue by sensai-jiraiya** [sensai-jiraiya/ecommerce-pattern-library#2]
### **Accessibility Checklist**

**Design & Structure**

- [x] Text size up (2 sizes)
_Yes, my text can size up to 2 sizes._

- [x] Text size down (2 sizes)
_Yes, my text can size down to 2 sizes._

- [x] Alt attribute tests
_Had to add in alt attributes, a lot of code was missing it._

- [x] Heading structure & outline
_Heading Structure was created when adding in type in the beginning._

- [x] ARIA implementation
_aria implementation added to areas necessary, will have to continue to monitor closely and not forget to add it in throughout my website when needed_.

- [x] Focus styles
_Focus styles are included._

- [x] Skip links

- [x] Colour contrast
_Colour contrast is decent, have to watch out with the colours of grey being used. Some are too light and have been changed to something that has more contrast_. 

- [x] Link obviousness 
_Links have been adjusted to be more obvious._

 @thomasjbradley

**Comment by thomasjbradley** [comment]
What about browser testing? Did you test the 5 major browsers? Did you test Edge?

**Comment by sensai-jiraiya** [comment]
@thomasjbradley, Sorry – I did test it on chrome, safari, firefox and opera. Had to re create my logo because i forgot to outline the text and it was changing the look in different browsers. 
I don't know what is Edge though, sorry I'm not really good at this.

**Comment by thomasjbradley** [comment]
https://www.microsoft.com/en-us/edge

**Comment by sensai-jiraiya** [comment]
OK, just tested on Edge, everything worked as expected on there as well. :)

**Comment by thomasjbradley** [comment]
:ok_hand:
